application: <Your Google Cloud Poject ID>
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "7d"

includes:
- web_api.yaml
- web_app.yaml

libraries:
#- name: endpoints
#  version: latest
- name: pycrypto
  version: latest
- name: jinja2
  version: "2.6"
